In [ ]:
#EXP-14
#databining and data formatting using python
#Riya NATEKAR
#25070123093

In [ ]:
import pandas as pd
import numpy as np

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_Sold':[25,60,35,80,50,15]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
#data bining
bins1 = [0, 10000, 30000, 60000] # Adjusted bins for Order_Value
labels1 = ['low' ,'medium' , 'high']
df['price_category'] = pd.cut(df['Price'], bins=bins1, labels=labels1) # Changed column and new category name
print(df)

      Product  Price  Units_Sold price_category
0      Laptop  55000          25           high
1      Mobile  20000          60         medium
2      Tablet  30000          35         medium
3  Headphones   2000          80            low
4  Smartwatch   8000          50            low
5      Camera  45000          15           high

In [ ]:
#BINNING UNITS SOLD
bins2 = [0, 30,60,100]
labels2 = ['Low Sales' , 'Medium Sales' , 'High Sales']
df['sales_category'] = pd.cut(df['Units_Sold'], bins=bins2, labels=labels2)
print(df)

      Product  Price  Units_Sold price_category sales_category
0      Laptop  55000          25           high      Low Sales
1      Mobile  20000          60         medium   Medium Sales
2      Tablet  30000          35         medium   Medium Sales
3  Headphones   2000          80            low     High Sales
4  Smartwatch   8000          50            low   Medium Sales
5      Camera  45000          15           high      Low Sales

In [ ]:
#data formatting
#convert data type

print(df.dtypes)

#df['Units_Sold'] =df['Units_Sold].astype(float)

#print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
price_category    category
sales_category    category
dtype: object

In [ ]:
#rounding values
df['Price'] = df['Price'].round(2)
print(df)

      Product  Price  Units_Sold price_category sales_category
0      Laptop  55000          25           high      Low Sales
1      Mobile  20000          60         medium   Medium Sales
2      Tablet  30000          35         medium   Medium Sales
3  Headphones   2000          80            low     High Sales
4  Smartwatch   8000          50            low   Medium Sales
5      Camera  45000          15           high      Low Sales

In [ ]:
#convert textto uppercase
df['Product'] = df['Product'].str.upper()
print(df)

      Product  Price  Units_Sold price_category sales_category
0      LAPTOP  55000          25           high      Low Sales
1      MOBILE  20000          60         medium   Medium Sales
2      TABLET  30000          35         medium   Medium Sales
3  HEADPHONES   2000          80            low     High Sales
4  SMARTWATCH   8000          50            low   Medium Sales
5      CAMERA  45000          15           high      Low Sales

In [ ]:
#sort data
sorted_df = df.sort_values(by='Price', )
print(sorted_df)

      Product  Price  Units_Sold price_category sales_category
3  HEADPHONES   2000          80            low     High Sales
4  SMARTWATCH   8000          50            low   Medium Sales
1      MOBILE  20000          60         medium   Medium Sales
2      TABLET  30000          35         medium   Medium Sales
5      CAMERA  45000          15           high      Low Sales
0      LAPTOP  55000          25           high      Low Sales

In [ ]:
sorted_df = df.sort_values(by='Price', ascending=False)
print(sorted_df)

      Product  Price  Units_Sold price_category sales_category
0      LAPTOP  55000          25           high      Low Sales
5      CAMERA  45000          15           high      Low Sales
2      TABLET  30000          35         medium   Medium Sales
1      MOBILE  20000          60         medium   Medium Sales
4  SMARTWATCH   8000          50            low   Medium Sales
3  HEADPHONES   2000          80            low     High Sales

In [2]:
import pandas as pd

data = {
'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
'Price':[55000,20000,30000,2000,8000,45000],
'Units_Sold':[25,60,35,80,50,15]
}

df = pd.DataFrame(data)

#data bining
bins1 = [0, 10000, 30000, 60000]
labels1 = ['low' ,'medium' , 'high']
df['price_category'] = pd.cut(df['Price'], bins=bins1, labels=labels1)

# Display unique values
print(df['price_category'].unique())

['high', 'medium', 'low']
Categories (3, object): ['low' < 'medium' < 'high']

In [ ]:
import pandas as pd
import numpy as np
data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
'Order_Value':[250,450,120,600,300,150,500,220],
'Delivery_Time':[30,45,25,60,35,20,50,28],
'Distance_km':[5,8,3,10,6,2,9,4]
}

df = pd.DataFrame(data)

display(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       O1          250             30            5
1       O2          450             45            8
2       O3          120             25            3
3       O4          600             60           10
4       O5          300             35            6
5       O6          150             20            2
6       O7          500             50            9
7       O8          220             28            4

In [ ]:
#count caterogrries
bins1 = [0, 250, 450, 650] # Define bins for Order_Value
labels1 = ['low' , 'medium' , 'high']
df['price_category'] = pd.cut(df['Order_Value'], bins=bins1, labels=labels1) # Create price_category for current df
print(df['price_category'].value_counts())
df

price_category
low       4
medium    2
high      2
Name: count, dtype: int64

  Order_ID  Order_Value  Delivery_Time  Distance_km price_category
0       O1          250             30            5            low
1       O2          450             45            8         medium
2       O3          120             25            3            low
3       O4          600             60           10           high
4       O5          300             35            6         medium
5       O6          150             20            2            low
6       O7          500             50            9           high
7       O8          220             28            4            low

In [4]:
import pandas as pd

# Re-create the df with order data to ensure 'Delivery_Time' column exists
data = {
'Order_ID':['O1','O2','O3','O4','O5','O6','O7','O8'],
'Order_Value':[250,450,120,600,300,150,500,220],
'Delivery_Time':[30,45,25,60,35,20,50,28],
'Distance_km':[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)


bins1 = [0, 250, 450, 650]
labels1 = ['low' , 'medium' , 'high']
df['price_category'] = pd.cut(df['Order_Value'], bins=bins1, labels=labels1)

# Binning delivery time
bins3 = [0,250,450,650]
labels3 = ['On Time','Delayed','Critical']
df['Delivery_time_Category'] = pd.cut(df['Delivery_Time'], bins=bins3, labels=labels3)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km price_category  \
0       O1          250             30            5            low
1       O2          450             45            8         medium
2       O3          120             25            3            low
3       O4          600             60           10           high
4       O5          300             35            6         medium
5       O6          150             20            2            low
6       O7          500             50            9           high
7       O8          220             28            4            low

  Delivery_time_Category
0                On Time
1                On Time
2                On Time
3                On Time
4                On Time
5                On Time
6                On Time
7                On Time